version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /cicd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /cicd/docker-credentials/password
    SONAR_TOKEN: /cicd/sonar/sonar-token

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Sonar Scanner..."
      - export SONAR_SCANNER_VERSION=4.7.0.2747
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH

  pre_build:
    commands:
      - echo "Starting SonarQube analysis..."

  build:
    commands:
      sonar-scanner \
        -Dsonar.projectKey=swiggy \
        -Dsonar.sources=. \
        -Dsonar.host.url=http://34.201.73.137:9000 \
        -Dsonar.login=sqp_a4c94f8747e04dc5a06f40bc41bae5cbd78bd4f9

  post_build:
    commands:
      - echo "Build + Sonar analysis completed"

artifacts:
  files:
    - appspec.yaml
